"""adding datetime

Revision ID: 9c0b42e172bc
Revises: 3d4aa7d35c2c
Create Date: 2019-02-25 00:23:44.514579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0b42e172bc'
down_revision = '3d4aa7d35c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'datetime')
    # ### end Alembic commands ###
